name: Test and build
on:
  push:
    branches: [main]
  pull_request:
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:

jobs:
  Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8.5"
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.1"
      - name: Install dependencies
        run: poetry install
      - name: Testing
        run: poetry run pytest
